### PR TITLE
[SPIR-V] Do no track splat vector constants

### PR DESCRIPTION
**Pull request by zuban32**
Fixes 'relationals' tests from #61

### CODE REVIEW

**Comment by iliya-diyachkov** [comment]
Currently the spirv code for these tests produced by LLVM-SPIRV-Backend and Translator is rather different. E.g. for transcoding/relationals_half.ll Backend produces:
```
        %16 = OpConstant %8 65535
...
        %49 = OpIsFinite %13 %46
        %50 = OpUndef %9
        %51 = OpCompositeInsert %9 %50 %16
        %52 = OpVectorShuffle %9 %51 %50 0
        %53 = OpUndef %9
        %54 = OpCompositeInsert %9 %53 %17
        %55 = OpVectorShuffle %9 %54 %53 0
        %56 = OpSelect %9 %49 %52 %55
```
while Translator gives this:
```
         %48 = OpConstantNull %v2ushort
         %50 = OpConstantComposite %v2ushort %ushort_65535 %ushort_65535
...
    %call3_0 = OpIsFinite %v2bool %f_0
     %call_0 = OpSelect %v2ushort %call3_0 %50 %48
```
I think it's ok for now, but later Backend should output the code similar to the one created by Translator.

**Comment by zuban32** [comment]
I believe that's some confusion introduced by the translator originally - it transforms scalar arguments for vector builtins into shuffle+insert (see transcoding/OpMin.ll as an example), whereas simple aggr constants are turned into OpConstantComposite.
There's no problem to fix that, I'll do it in a separate PR

**Comment by zuban32** [comment]
Added to this PR, fixed other tests from #61 - all are passing except for lshr-constexpr, it now fails just as before (there's a problem with long integers selection there)

**Comment by iliya-diyachkov** [comment]
> 
> 
> I believe that's some confusion introduced by the translator originally - it transforms scalar arguments for vector builtins into shuffle+insert (see transcoding/OpMin.ll as an example), whereas simple aggr constants are turned into OpConstantComposite. There's no problem to fix that, I'll do it in a separate PR

Yes, the translator generates strange spirv for transcoding/OpMin.ll. Looks like it uses a different approaches for intrinsics with vector args and scalar args which should be promoted to vector args (visitCallScalToVec() in lib/SPIRV/OCLToSPIRV.cpp).

**Comment by iliya-diyachkov** [comment]
> Added to this PR, fixed other tests from #61 - all are passing except for lshr-constexpr, it now fails just as before (there's a problem with long integers selection there)

Thanks! It looks fine but now the backend puts some composite constants inside function bodies (see transcoding/relationals_float.ll or transcoding/relationals_double.ll) and duplicates them:
```
        %47 = OpIsFinite %12 %44
        %48 = OpConstantComposite %8 %15 %15
        %49 = OpConstantComposite %8 %14 %14
        %50 = OpSelect %8 %47 %48 %49
        %51 = OpIsNan %12 %44
        %52 = OpConstantComposite %8 %15 %15
        %53 = OpConstantComposite %8 %14 %14
        %54 = OpSelect %8 %51 %52 %53
```
I revert deleted "DT.add(ConstVec, &MIRBuilder.getMF(), spvVecConst);" and it works with correct processing of composits in these tests.

**Comment by zuban32** [comment]
> I revert deleted "DT.add(ConstVec, &MIRBuilder.getMF(), spvVecConst);" and it works with correct processing of composits in these tests.

That's right, I removed it when we used shuffle, but now it should be reinstated, I just missed that.

And FYI, we now have some [small] part of the translator's OCLToSPV - see SPIRVOCLRegularizer.cpp, for now it just handles the aforementioned vector args problem for small subset of builtins.

**Comment by iliya-diyachkov** [comment]
Nice, thanks!

**Comment by iliya-diyachkov** [comment]
@zuban32 will you fix and merge this PR or maybe I will do it for you.

**Comment by iliya-diyachkov** [comment]
Unfortunately you have not reverted "DT.add(ConstVec, &MIRBuilder.getMF(), spvVecConst);".

**Comment by zuban32** [comment]
> I revert deleted "DT.add(ConstVec, &MIRBuilder.getMF(), spvVecConst);" and it works with correct processing of composits in these tests.

I got it as you've already done this in one of the other PRs, sorry for misunderstanding

**Comment by iliya-diyachkov** [comment]
No problem, I'll remove it myself in the next PR.

**Pull request merged**
