### PR TITLE
[SPIR-V] Allow implicit DCE during InstSelection by marking ASSIGN_TYPE as 'hasNoSideEffects'.

### PR DESCRIPTION
**Pull request by zuban32**

### CODE REVIEW

**Comment by iliya-diyachkov** [comment]
Why we need DCE? Is this required for topological sorting? Can it increase difference in output between the backend and the translator (which is not very good for our project in the current state)?

**Comment by zuban32** [comment]
Nope, topological sorting has nothing to do with that. I've just notice that for cases where our selector uses `foldImm` (e.g. for `extract/insert_value` index literals) those folded `G_CONSTANT`s are left dead and nothing is currently able to remove them. And since we removed `SPIRVInstructionSelector`'s overriding version of `runOnMachineFunction` there's no proper way to do it there. As for the translator divergence - I'm curious to see OCL testing results, there was only one passing LIT affected.

**Comment by zuban32** [comment]
@iliya-diyachkov FYI CTS testing proves no regression happen in CTS testing due to this.

**Comment by iliya-diyachkov** [comment]
I'm comparing CTS results of pr171 and pr172 and see the difference: 2 new passes and 4 new fails. 
```
ulong_math	integer_ops	FINISHED	PASS
ulong_shift	integer_ops	FINISHED	PASS

svm_shared_sub_buffers	SVM	INTERRUPTED	FAIL
svm_shared_address_space_coarse_grain_old_api	SVM	INTERRUPTED	FAIL
svm_shared_address_space_coarse_grain_new_api	SVM	INTERRUPTED	FAIL
svm_cross_buffer_pointers_coarse_grain	SVM	INTERRUPTED	FAIL
```

The fails will apparently disappear after rebase, so we'll get 2 new passes.

But probably @andreytr4intel needs to take a look at the changes in lshr-constexpr.ll because he added the test.

**Pull request merged**
