### PR TITLE
[SPIR-V] Ensure proper types assignment for aggregates

### PR DESCRIPTION
**Pull request by zuban32**
Previously all SPIRV-specific intrinsic intended for
aggregates handling had 'fake' i32 type assigned according
to their LLVM IR signatures. Now we generate 'assign_type's
earlier using actual LLVM aggregate types.

Thanks to incomplete transcoding/extract_insert_value.ll test
that wasn't found before. Now the test is fixed as well.

### CODE REVIEW

**Comment by iliya-diyachkov** [comment]
Probably instructions/nested-composites.ll test degraded after this merge. Now we have the compile fail:
```
: 'RUN: at line 1';   /export/users/idiyachk/spirv/build_old_be/bin/llc -O0 -global-isel /export/users/idiyachk/spirv/LLVM-SPIRV-Backend-2/llvm/test/CodeGen/SPIRV/instructions/nested-composites.ll -o - | /export/users/idiyachk/spirv/build_old_be/bin/FileCheck /export/users/idiyachk/spirv/LLVM-SPIRV-Backend-2/llvm/test/CodeGen/SPIRV/instructions/nested-composites.ll
--
Exit Code: 2

Command Output (stderr):
--
LLVM ERROR: unable to translate instruction: call (in function: producer)
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
```
Before it was compiled and had "wrong output" error:
```
Command Output (stderr):
--
/export/users/idiyachk/spirv/LLVM-SPIRV-Backend-2/llvm/test/CodeGen/SPIRV/instructions/nested-composites.ll:21:14: error: CHECK-DAG: expected string not found in input
; CHECK-DAG: [[UNDEF_TY2:%.+]] = OpUndef [[TY2]]
             ^
...
```
@zuban32 please check and fix.

**Comment by zuban32** [comment]
It shouldn't have to as I ran full LIT suite locally and passrate was just the same. BTW I don't remember it passing at all

UPD. I see, it's still related to processing of 'undef's. Will fix that

**Comment by iliya-diyachkov** [comment]
Sure, but the LIT testing does not check "wrong output" => "compilation fail" degradation. It only distinguish "pass" or "fail" status. However the test fails differently now. It does not require urgent patching, but it would be nice to investigate the failure and return it to previous state in the future.

**Comment by zuban32** [comment]
Just for the record - I don't think that in general 'degradation' is a correct term for  "wrong output" => "compilation fail" case and that it should be fixed itself, for the obvious reasons. Don't want to have a long discussion about that here, of course there might be some cases where tests show wrong output due to e.g. missing functionality and then we make them fail due to the newly introduced compilation failure not related to the original stuff at all, but that's a relatively rare case.

PS In case of LITs IMO only actual passrate matters since they're the simplest level of tests available for us.

**Comment by iliya-diyachkov** [comment]
You are right, sometimes the change can discover an error, sometimes it indicates the progress. We just have to make sure that we are dealing with the second case.

**Pull request merged**
