### PR TITLE
[SPIR-V] fix adding to DT in addConstantsToTrack

### LINKED ISSUE #59: Assertion `OldReg == R' failed in SPIRVDuplicatesTracker.h
6 tests fails after 906a4a8 (#52)  on the assertion `OldReg == R' in SPIRVDuplicatesTracker.h:
```
transcoding/isequal.ll
transcoding/OpAllAny.ll
transcoding/OpImageQuerySize.ll
transcoding/check_ro_qualifier.ll
transcoding/OpImageSampleExplicitLod.ll
opencl/image.ll
```
+2 after #57 :
```
transcoding/builtin_vars_opt.ll
transcoding/OpImageReadMS.ll
```

### PR DESCRIPTION
**Pull request by iliya-diyachkov**
The change corrects adding of constants and global values to DT in addConstantsToTrack (SPIRVIRTranslator.cpp). It fixes #59 issue.

About additional 12 tests are expected to pass if we apply this patch after #62 and #63, so the LIT pass rate is going to be 116/221 after applying all 3 patches.

### CODE REVIEW

**Comment by zuban32** [comment]
Ok, let these checks be there for now. But in general I don't fully understand we we need them, perhaps something is not right in our design, I'll look into that

**Comment by iliya-diyachkov** [comment]
If we already have (and keep in DT) a register which holds a constant value, we have to use it instead of adding new one with the same constant. It prevents from constant duplication.

**Comment by zuban32** [comment]
I see, in that case I'd say that eventually DT API needs to be improved to incapsulate these checks to remove them from the other code

**Comment by iliya-diyachkov** [comment]
Ok, I'll implement it later.

**Pull request merged**
